### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-palomaviolin#1]
Really cool job @palomaviolin  !!!

Here you have some tips to improve the exercise:

- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Avoid extra `div`s around input and button. You don't need them right now.
- [x] Define the logic to generate and save the random number (remember we gave you a sample code)
- [x] Use `addEventListener` instead of `onClick` to register event listeners
- [ ] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Remove commented code
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

//Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by palomaviolin** [comment]
@nasivuela I've finished the game, so you can take a look again. Thanks!

**Comment by nasivuela** [comment]
Good work @palomaviolin !!

I'm closing this, but here you have more tips to keep improving it:
- Watch out your `<partial>` tag on index.html, the attributes `src` and `label` should be inside the open tag, not between open and close.
- Inside `testGuess` function (the handler of click on the button) you are accessing the DOM and searching for an element with id `number-button`. Instead of doing it every time the user clicks you could do it once when the page loads (outside the function).
- Do not forget oto end your sentences with `;`, example `feedbackElem.innerText = '¡HAS GANADO, CAMPEONA!';`
 Since you are writing multiple times `feedbackElem.innerText = 'something'` you could move that logic to a function and reuse it!
- What do you think about adding a reset functionality?
- ... and whatever else you want to do to practice ;)

![](https://media.giphy.com/media/VarW8M9eEha1y/giphy.gif)
